### ISSUE TITLE
No messages on Telegram BOT

### ISSUE THREAD

**Issue by protontrigg3r** [anhbh310/gotify2telegram#1]
I tried to send a notification from Proxmox, both to the Gotify APPS "Proxmox" and directly to the auto generated application "Gotify 2 Telegram". The message arrives on Gotify but the messages are not forwarded to Telegram.

Logs do not show errors. How can I debug?

This is the configuration:

![0-apps](https://github.com/anhbh310/gotify2telegram/assets/38140509/ad0618cd-cf61-4390-a83d-5ced4a62eb87)

![1-client](https://github.com/anhbh310/gotify2telegram/assets/38140509/c983f074-de8e-4305-b359-53b7172299d1)

![2-inst](https://github.com/anhbh310/gotify2telegram/assets/38140509/52d3b538-1fe0-4690-bb20-e65c3a1ab036)

![3-service](https://github.com/anhbh310/gotify2telegram/assets/38140509/caf941cb-e004-4882-80a6-e67c873dd58d)

![4-service_status](https://github.com/anhbh310/gotify2telegram/assets/38140509/1df9ff36-285c-411b-9572-3d8a20889d8e)

![5-env_var](https://github.com/anhbh310/gotify2telegram/assets/38140509/ffb30ba4-8be1-49c4-b64a-1f0c42c215af)

![6-log](https://github.com/anhbh310/gotify2telegram/assets/38140509/d7ac9b7d-2404-42c5-a43b-a4d960e66dd4)

**Comment by anhbh310** [comment]
Hello @protontrigg3r,

I apologize for the delayed response. I've built a deployment environment like yours, and everything works fine.

Could you please check the following:

- Is your GOTIFY_CLIENT_TOKEN value correct?
- Please check the port value in YOUR_GOTIFY_IP. If you are running Docker, the port value must be set to the application's port in the container (default is 80).

Let me know if you need any more help!

**Comment by tchekoto** [comment]
I observed the same issue.
However, the testing works, is there a limit on the message size?

**Comment by anhbh310** [comment]
> I observed the same issue. However, the testing works, is there a limit on the message size?

Hello @tchekoto, I've created a long message and sent it to the Gotify server. Everything ran perfectly.

On Gotify dashboard:
![image](https://github.com/anhbh310/gotify2telegram/assets/32455127/595e9a83-38a4-4aad-9855-17cfccbac677)

On telegram:
![image](https://github.com/anhbh310/gotify2telegram/assets/32455127/afdac75d-6d7b-40b6-84fe-8ca5c7370bdd)

**Comment by tchekoto** [comment]
A backup report from Proxmox is like 25k chars on 322 lines.

Can you try with this size ?
Lorem ipsum generator might help: https://www.lipsum.com/

**Comment by anhbh310** [comment]
Hi @tchekoto,

Currently, the Telegram Bot API only supports 4096 characters per message (Ref: [Telegram Bot API](https://core.telegram.org/bots/api#sendmessage)).

If you still want to send your Proxmox report, I'll add support for longer messages in the next release.

**Comment by tchekoto** [comment]
Hi
Thank you for the investigation and the explanation.

Would it be possible to truncate long message ? Maybe with a parameter (4096 char seam to be touch much anyway in a log and the top of the report contains the details).

**Comment by anhbh310** [comment]
To tackle this problem, I'm thinking of two solutions:

- I will break the report into many sub-messages, then send them consecutively to your Telegram.
- Or I will compress it into a file (html, pdf or zip) so you can download and view it.

Which option do you prefer? Just let me know.
Thank you!

**Comment by tchekoto** [comment]
Can you pick option 1 and leave an option to send the first message only ?

**Comment by protontrigg3r** [comment]
Hello @anhbh310 and thanks for your help

> Is your GOTIFY_CLIENT_TOKEN value correct?

Yes, I copy-and-paste the value from Gotify interface to gotify.service

>  Please check the port value in YOUR_GOTIFY_IP. If you are running Docker,

I'm not using Docker, so I set the port where the service is running (3000).

`ss -lnp | grep gotify`

`tcp   LISTEN 0      4096               *:3000           *:*    users:(("gotify",pid=624,fd=9))`

**Comment by protontrigg3r** [comment]
>   I will break the report into many sub-messages, then send them consecutively to your Telegram.

For me this would be fine

**Comment by protontrigg3r** [comment]
I updated the Gotify server to version 2.5.0 and gotify2telegram to version 1.1.0 but still haven't been able to get things working.

The logs do not report errors and the test message sent by Proxmox is delivered on Gotify but not on the Telegram channel (where I turn off the Group Privacy setting).

There appears to be no communication between the Gotify server and the gotify2telegram client. I checked the values ​​of GOTIFY_CLIENT_TOKEN/TELEGRAM_CHAT_ID/TELEGRAM_BOT_TOKEN several times, so I guess the problem might be the value of GOTIFY_HOST.

I'm not using SSL so the Gotify server runs in plain HTTP on port 3000 (to use port 80 I would have to run gotify as root...): It is possible that the problem remains on "**GOTIFY_HOST=ws:/ /localhost:3000**" setting?

**Comment by protontrigg3r** [comment]
In case it may be useful to others: from console I run:

`curl https://api.telegram.org/bot<bot-api-token>/getUpdates`

The output give me a new Chat-ID value and after updating the environment variable TELEGRAM_CHAT_ID with this value, everything was fine.

**Comment by anhbh310** [comment]
> In case it may be useful to others: from console I run:
> 
> `curl https://api.telegram.org/bot<bot-api-token>/getUpdates`
> 
> The output give me a new Chat-ID value and after updating the environment variable TELEGRAM_CHAT_ID with this value, everything was fine.

Glad to know that, thanks for sharing. If you want to contribute to the project, please add your contributions to the README.md and create a pull request.


> Can you pick option 1 and leave an option to send the first message only ?



> > I will break the report into many sub-messages, then send them consecutively to your Telegram.
> 
> For me this would be fine

Regarding handling long messages, I've added a new feature inspired by your suggestions. You can get it from the latest release [v1.1.1](https://github.com/anhbh310/gotify2telegram/releases/tag/v1.1.1). However, these pre-built .so files only support Gotify v2.5.0. If you want to use other versions, please recompile it from source.
