### ISSUE TITLE
Gotify 2.1.6 Compatibility

### ISSUE THREAD

**Issue by Aristocrat-jt** [anhbh310/gotify2telegram#10]
Seems it's not longer works with latest Gotify. 

Is it compatible with Gotify 2.1.6 or just me?

**Comment by gaalma** [comment]
I think you meant 2.6.1.
This is an issue with Gotify plugins... they only work with the version they were compiled for. 
I reverted my Gotify version to 2.5.0 since this plugin currently supports it.

**Comment by anhbh310** [comment]
Hi @Aristocrat-jt, @gaalma 

Thank you for letting me know about the new version of Gotify. It's true that the plugin is version-specific.
Here is the new [release](https://github.com/anhbh310/gotify2telegram/releases/tag/v1.2.0) for Gotify 2.1.6. Please give it a try and inform me if you encounter any issues.

**Comment by Flummi** [comment]
It works, thank you very much.

**Comment by Aristocrat-jt** [comment]
Thanks for the quick update.
