### ISSUE TITLE
Release version doesn't work with latest Gotify version

### ISSUE THREAD

**Issue by gaalma** [anhbh310/gotify2telegram#2]
Hi,

Since the last gotify update, gotify2telegram breaks gotify. Log shows gotify complaining that plugin was not compiled with latest version and simply breaks gotify.

The only solution is to remove gotify2telegram from plugins folder and restart. I did not try to build it with the new gotify image.

Thanks,
Gabriel

**Comment by anhbh310** [comment]
Hi,

Sorry for the delayed response. I've built the plugin to adapt to Gotify 2.5.0. You can get it from release [v1.1.0](https://github.com/anhbh310/gotify2telegram/releases/tag/v1.1.0).
Let me know if you need any further assistance!

Thank you for your feedback. I appreciate it.

Anh

**Comment by gaalma** [comment]
Hi,

It is working properly now with the new version.
I'm closing the issue.

Thank you!
Gabriel
